// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)

void onAutoOffChange();
void onPumpStatusChange();
void onRelayStatusChange();

CloudCounter auto_off;
float humidity;
float temperature;
bool pump_status;
bool relay_status;

void initProperties(){

  ArduinoCloud.addProperty(auto_off, READWRITE, ON_CHANGE, onAutoOffChange);
  ArduinoCloud.addProperty(humidity, READ, 20 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperature, READ, 20 * SECONDS, NULL);
  ArduinoCloud.addProperty(pump_status, READWRITE, ON_CHANGE, onPumpStatusChange);
  ArduinoCloud.addProperty(relay_status, READWRITE, ON_CHANGE, onRelayStatusChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
